# Datenstrom Yellow extension settings

Extension: Calendar
Version: 0.3.1
Description: Show upcoming dates from a calendar link.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-calendar/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-calendar
DocumentationLanguage: en, de
Published: 2026-09-28 12:14:47
Status: experimental
system/workers/calendar.php: calendar.php, create, update
