# Datenstrom Yellow extension settings

Extension: Calendar
Version: 0.2.0
Description: Show upcoming dates from a calendar link.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-calendar/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-calendar
DocumentationLanguage: en, de
Published: 2026-09-28 11:08:11
Status: experimental
system/workers/calendar.php: calendar.php, create, update
